"""empty message

Revision ID: f3c6f674e1b4
Revises: 43bb3f282360
Create Date: 2022-08-04 12:05:10.754899

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f3c6f674e1b4'
down_revision = '43bb3f282360'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('groups', sa.Column('created_on', sa.DateTime(), nullable=False))
    op.add_column('groups', sa.Column('updated_on', sa.DateTime(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('groups', 'updated_on')
    op.drop_column('groups', 'created_on')
    # ### end Alembic commands ###
